In [1]:
import numpy #why importing this library #numericalpython-->numpy

In [2]:
print (numpy.__version__)

1.26.4


In [18]:
print (pandas.__version__) #checking name error -->variable is not defined and you get name error as pandas is not imported

2.2.2


In [4]:
#pandas is not imported

In [5]:
import pandas #why importing this library

In [6]:
print (pandas.__version__)

2.2.2


In [7]:
#Suyash Pandit as [aliasing] as Ash --> giving a short name --> alias like of spies

In [8]:
#numpy alias as np
#pandas alias as pd --> is helpful as language for the community

In [9]:
import pandas as pd

In [10]:
print (pd.__version__)

2.2.2


In [13]:
import numpy as np

In [15]:
#creating a simple 1D array np.array()
# assuming this is a list of values i need to convert into numpy array [1,2,3,4,5,6]
np_arr1 = np.array ([1,2,3,4,5,6])
print (np_arr1)

[1 2 3 4 5 6]


In [16]:
np.array ([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [17]:
print (np.array ([1,2,3,4,5,6]))

[1 2 3 4 5 6]


In [19]:
#array properties
arr1 = np.array([1,2,3])
print (arr1)

[1 2 3]


In [29]:
arr1.ndim #checking the number of dimensions


1

In [30]:
arr1.shape

(3,)

In [44]:
arr2 = np.array ([[1,2,3],[4,5,6]]) #making 2d array 
print (arr2)
arr2.ndim

[[1 2 3]
 [4 5 6]]


2

In [31]:
arr2.shape

(2, 3)

In [38]:
arr3 = np.array ([[[1,2,3],[4,5,6], [7,8,9]]]) #making 3d array even when it is just with adding square brackets and no number inside
arr3.ndim

3

In [35]:
print (arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [36]:
#shapes
arr3.shape #(block,rows,column) 

(1, 3, 3)

In [27]:
arr4 = np.array ([[[[1,2,3],[4,5,6]]]])
arr4.shape #groups,block,row,columns

(1, 1, 2, 3)

In [39]:
#accessing elements
print(arr1[1]) #output 2

2


In [45]:
print(arr2[1,2]) #second row, third column

6


In [49]:
print(arr3[0,2,1]) #first block, third row,second column #output 8 

8


In [66]:
#slicing
arr1=np.array([1,2,3,4,5,6,7]) #when you slice, the last element is not printed, it is not element minus 1 index. it is the element's index you need to put
print (arr1[0:4])

[1 2 3 4]


In [56]:
arr1[:]

array([1, 2, 3, 4, 5, 6, 7])

In [61]:
arr1[1:6] #only printing 2 to 6

array([2, 3, 4, 5, 6])

In [67]:
arr1[-5:-1] #start from 7 and end at 3 but notice u need to put the 

array([3, 4, 5, 6])

In [70]:
#itemsize
itemarr=np.array([2,4,6,8,10])
itemarr.itemsize

4